services:
  postgres:
    image: postgres:15
    container_name: smartbadminton-postgres
    environment:
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: smartbadminton
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: smartbadminton-redis
    ports:
      - "6379:6379"

  backend:
    build:
      context: ../backend
      dockerfile: ../infra/Docker/Dockerfile.BE
    container_name: smartbadminton-backend
    env_file:
      - ../backend/.env
    environment:
      DATABASE_URL: postgresql://postgres:admin123@postgres:5432/smartbadminton
      REDIS_URL: redis://redis:6379
    ports:
      - "3000:3000"
    depends_on:
      - postgres
      - redis

volumes:
  postgres_data:
