services:
  postgres:
    image: postgres:15
    container_name: smartbadminton-postgres
    environment:
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: smartbadminton
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: ../backend
      dockerfile: ../infra/Docker/Dockerfile.BE
    container_name: smartbadminton-backend
    env_file:
      - ../backend/.env
    environment:
      DATABASE_URL: postgresql://postgres:admin123@postgres:5432/smartbadminton
    ports:
      - "3000:3000"
    depends_on:
      - postgres

volumes:
  postgres_data:
